name: GMW Backend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Step 1 Checkout master branch from Github
      uses: actions/checkout@v3
      
    - name: Step 2 - Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Step 3 - Build MGW backend
      run: | 
        mvn -B package --file pom.xml
        mkdir staging && cp target/*.jar staging
      
    - name: Step 4 - Set up cache for Maven
      uses: actions/cache@v3.2.3
      with:
          path: ~/m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
    
    - name: Step 5 - Persist workflow data as artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
           name: gmw
           path: staging
