name: GMW Backend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Step 1 Checkout master branch from Github
        uses: actions/checkout@v3

      - name: Step 2 - Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Step 3 - Setup maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2

      - name: Step 4 - Run unit tests
        run: mvn clean package

      - name: Rename the artifact
        run: cp api/target/api-0.0.1-SNAPSHOT.jar gmw-api.jar

      - name: Save the artifact
        uses: actions/upload-artifact@master
        with:
          name: gmw-api
          path: gmw-api.jar